#!/bin/bash

set -eux

script_dir=$(dirname "$0")
base_dir="$script_dir/.."
cd "$base_dir"

docker build protoc-go -t mackerel-demo-gocon-2025-protoc-go

## account
mkdir -p go/account
docker run -v "$(pwd):/pb" -w /pb --rm mackerel-demo-gocon-2025-protoc-go \
  protoc \
    --go_out=go/account \
    --go_opt=paths=source_relative \
    --go-grpc_out=go/account \
    --go-grpc_opt=paths=source_relative \
    account.proto
mkdir -p ../services/account/pb ../services/blog/pb
cp -r ./go/account ../services/account/pb
cp -r ./go/account ../services/blog/pb

## renderer
mkdir -p go/renderer
docker run -v "$(pwd):/pb" -w /pb --rm mackerel-demo-gocon-2025-protoc-go \
  protoc \
    --go_out=go/renderer \
    --go_opt=paths=source_relative \
    --go-grpc_out=go/renderer \
    --go-grpc_opt=paths=source_relative \
    renderer.proto
mkdir -p ../services/renderer/pb ../services/blog/pb
cp -r ./go/renderer ../services/renderer/pb
cp -r ./go/renderer ../services/blog/pb
